### ISSUE TITLE
Elastoplastic realization question

### ISSUE THREAD

**Issue by RokyC** [michalhabera/dolfiny#13]
Hello, I'm very excited that libraries like dolfiny make it easier to implement universal material constitutive under fenicsx. I was wondering if you could share a tutorial on viscoplastic constitutive variational theory? Because while I learned in the demo program, the ```dλ = ufl.max_value(f, 0)``` and  the reinforcement criteria represented by ```bh, qh, bb and qb``` on solid_plasticity_monolithic.py are somewhat unclear.Thanks very much!

**Comment by Malkut79** [comment]
It would be good just to add any reference book or paper.

**Comment by anzil** [comment]
Thanks for your feedback. I have added some references and further comments directly in the demo code, that could be helpful.

- https://doi.org/10.1007/978-94-011-2860-5_66
- https://doi.org/10.1016/j.commatsci.2012.05.062
- https://doi.org/10.24355/dbbs.084-202112170722-0
